### ISSUE TITLE
Improvements to Login page

### ISSUE THREAD

**Issue by divyansh14kr** [BharatSeva/BharatSeva-Plus-User-Interface#10]
the current login page has issues with the alignments with the google logo.
the register here button overlaps the drop shadow 
please assign me this issue to fix them.
![Screenshot 2024-10-15 at 3 55 11 PM](https://github.com/user-attachments/assets/46657679-3e2b-45a7-947d-e739b0a0efa8)

**Comment by divyansh14kr** [comment]
also fonts in the point to note section can be improved

**Comment by Priyanshuraj21030** [comment]
Can you assign me to improve it

**Comment by vaibhavyadav-dev** [comment]
@divyansh14kr @Priyanshuraj21030 this page belongs to [Healthcare Interface](http://4.236.178.190:5000/healthcare/), and it is already assigned to someone, try to look for new bug or feature in this User Interface, create issue, get assigned and started working, [Visit here](url) to know more about this project.
If you've any issue drop your message I'll help you out.

**Comment by Priyanshuraj21030** [comment]
Is there any task I can do to contribute from my side
