### ISSUE TITLE
Improve the UI for the login page

### ISSUE THREAD

**Issue by RakinduM** [BharatSeva/BharatSeva-Plus-User-Interface#11]
I would like improve the UI of the login page and like to use tailwind for it. Consider and assign me to work on it

**Comment by vaibhavyadav-dev** [comment]
Hello @RakinduM  Thank you for your interest on this issue. Before we proceed, could you please share your plan on how you intend to approach this task? 
Let’s align on the approach before you begin working.

**Comment by RakinduM** [comment]
<img width="563" alt="Screenshot 2024-10-15 at 21 17 03" src="https://github.com/user-attachments/assets/abd334e1-9db2-49fe-b535-814053985ffb">

Login Form/Registration Form should be the center of the page.
Color combinations can be more improve.
Sign up with google button not displayed correctly.
Input fields can be make more UI rich.

I would use tailwind as you mention to use tailwind another issue.

**Comment by vaibhavyadav-dev** [comment]
ok @RakinduM that's look good you can take this issue and try to add some beautiful UI in login to look good.

**Comment by vaibhavyadav-dev** [comment]
@RakinduM pull the lates commits and work on it

**Comment by RakinduM** [comment]
@vaibhavyadav-dev as someone already created the login and signup pages as the design, I put the logo to the it.. Please check the PR.
