### ISSUE TITLE
Avoid multiple Register submits

### ISSUE THREAD

**Issue by karthik-script** [BharatSeva/BharatSeva-Plus-User-Interface#16]
Hi @vaibhavyadav-dev  , I can fix this issue for you. Please assign it to me. Thanks.
Also, can you please add Labels on this for **Hactoberfest**? Thanks.

Description:
When a user attempts to register, clicking the “Register” button multiple times in quick succession triggers multiple submit requests. This can lead to redundant requests being sent to the server, potentially causing performance issues or duplicate registrations.

Steps to Reproduce:

	1.	Navigate to the registration page.
	2.	Enter valid registration details in all required fields.
	3.	Click the “Register” button multiple times rapidly.
	4.	Observe that multiple submit requests are sent to the server.

Expected Behavior:
Only one registration submit request should be sent, even if the user clicks the “Register” button multiple times.

Current Behavior:
Multiple requests are sent if the “Register” button is clicked repeatedly.

Proposed Solution:
Disable the “Register” button and display a loading state immediately after the first click until the registration process is complete.

**Comment by vaibhavyadav-dev** [comment]
Great work @karthik-script You’ve identified some crucial UI/UX issues that we hadn't noticed before. I’d appreciate it if you could take this one and also apply similar improvements to the **Login Page** for consistency across the platform.
