### ISSUE TITLE
[UI/UX Improvement]: Enhance Activity Log Section for Better User Experience

### ISSUE THREAD

**Issue by vaibhavyadav-dev** [BharatSeva/BharatSeva-Plus-User-Interface#17]
**Description**
The current design of the Activity Log section can be improved to provide a cleaner, more user-friendly experience.

![image](https://github.com/user-attachments/assets/17874976-452e-4149-a4ef-dfb7443c4880)

### **Tasks**
1. **Improve Contrast and Readability:**
   - Increase contrast between text and background for better clarity (e.g., light text on darker backgrounds).
   - Adjust font sizes to improve readability, especially for section headers and log details.

2. **Implement Card-Based Layout:**
   - Reorganize log entries for "HealthCare", "Location", and "Date" horizontally within cards for a compact and easy-to-scan layout.
   - Ensure consistent spacing between elements.

3. **Simplify Date/Time Format:**
   - Simplify the date and time format to: `DD MMM YYYY, HH:MM` (e.g., `16 Oct 2024, 19:10`).
   - Use tooltips or small icons for more advanced time details like UTC offset.

### **Additional Notes**
- Maintain a modern, slightly lighter theme to make the interface feel fresh and user-friendly.

**Comment by vaibhavyadav-dev** [comment]
@matinshaikh31 share your idea before you begin working on this issue

**Comment by Tanish2207** [comment]
Hi!
Can you please assign me for this issue. 
Below I have attached a figma screenshot for the idea what I thought of.
1. The text is more readable, UI is clear and easy-to-read.
2. The content is organised into cards for an easy-to-scan layout. I have used a consistent standard spacing in each element.
3. The date and time format will be formatted as required.

![image](https://github.com/user-attachments/assets/006f090f-28f8-4d4e-ab34-9517121df1fd)

**Comment by vaibhavyadav-dev** [comment]
ok @Tanish2207 you suggestion look great to me, you can take this, and make sure the latest log appear top in respective section list
