### ISSUE TITLE
Improvement in UI of login/signup page

### ISSUE THREAD

**Issue by rohitja26** [BharatSeva/BharatSeva-Plus-User-Interface#19]
The UI of the signup/login page is very worst and need to be improved. I can help you with that by improving the UI of the signup page

**Comment by vaibhavyadav-dev** [comment]
@rohitja26 @matinshaikh31I would appreciate, if can you make like this 
**NOTE: AI GENERATED IMAGE**


![image](https://github.com/user-attachments/assets/37106eaf-9faf-4aae-a437-9b1a4ced2e03)


This is suggested Upgrade for Healthcare Portal but you can adjust it for Patient/User

**Comment by matinshaikh31** [comment]
ok i will try just assign me this issue
