### ISSUE TITLE
Include a footer section

### ISSUE THREAD

**Issue by Anirban780** [BharatSeva/BharatSeva-Plus-User-Interface#20]
@vaibhavyadav-dev I have seen the website and it lacks a footer section. So i want to add it along with contact us part and social media icons.

**Comment by vaibhavyadav-dev** [comment]
@Anirban780 why don't you guys read contributing guidelines, you opened a issue without even looking at it ?
don't you know it's spam, you'll be permanently blocked from repos for such things.
