### ISSUE TITLE
[Security] Resolve Multiple Vulnerabilities Detected in NPM Packages

### ISSUE THREAD

**Issue by vaibhavyadav-dev** [BharatSeva/BharatSeva-Plus-User-Interface#26]
## Description
A number of vulnerabilities were detected in the following NPM packages. Immediate action is required to mitigate potential security risks.

## List of Vulnerabilities:
1. **Babel** - Arbitrary code execution
   _Severity_: Critical  
   _Affected Package_: babel/traverse

2. **path-to-regexp** - Backtracking regular expressions 
   _Severity_: High  
   _Affected Package_: path-to-regexp

3. **axios** - Server-Side Request Forgery 
   _Severity_: High  
   _Affected Package_: axios

4. **braces** - Uncontrolled resource consumption
   _Severity_: High  
   _Affected Package_: braces

5. **semver** - Regular Expression Denial of Service (ReDoS)
   _Severity_: High  
   _Affected Package_: semver

6. **nth-check** - Inefficient Regular Expression Complexity
   _Severity_: High  
   _Affected Package_: nth-check

7. **rollup** - DOM Clobbering Gadget leads to XSS 
   _Severity_: High  
   _Affected Package_: rollup

8. **body-parser** - Denial of Service with URL Encoding 
   _Severity_: High  
   _Affected Package_: body-parser

9. **@adobe/css-tools** - ReDoS while parsing CSS 
   _Severity_: Moderate  
   _Affected Package_: @adobe/css-tools

## Steps to Reproduce:
1. Review the vulnerabilities in `package-lock.json`.
2. Identify the versions of the affected packages.
3. Update to the latest patched versions or remove vulnerable packages where possible.

## Expected Outcome:
- All identified vulnerabilities should be addressed, either through version upgrades or patches, to ensure system security and stability.

## Labels:
- Security, High Priority

**Comment by kalyan90** [comment]
@vaibhavyadav-dev I can look into this one, can you please assign this to me?

**Comment by kalyan90** [comment]
@vaibhavyadav-dev PR has been submitted to address this issue https://github.com/BharatSeva/BharatSeva-Plus-User-Interface/pull/28

**Comment by vaibhavyadav-dev** [comment]
ok @kalyan90
