### ISSUE TITLE
Issue: Fix ESLint errors in project 

### ISSUE THREAD

**Issue by vaibhavyadav-dev** [BharatSeva/BharatSeva-Plus-User-Interface#4]
The project build have several ESLint errors and warnings.
## To Reproduce:
- Run the build process using:
    ```
    npm run build
    ```
- Observe the build fails due to the above issues.

## Acceptance Criteria:
- The build process runs successfully without any ESLint errors or warnings.
- Unused variables are removed or utilized in the code.
- Missing dependencies are addressed in useEffect hooks.

**Comment by kalyan90** [comment]
@vaibhavyadav-dev I can check this one

**Comment by Vixs101** [comment]
Hi @vaibhavyadav-dev can this issue be assigned to me?

**Comment by vaibhavyadav-dev** [comment]
Ok @Vixs101 ! you can take this issue.

**Comment by vaibhavyadav-dev** [comment]
@kalyan90 try to find bugs in this project, you've to be fishy, or is there something you think you can add new feature if there is, raise issue, get assigned and start working on it.
