### ISSUE TITLE
Include CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by Dhruv-Davda** [BharatSeva/BharatSeva-Plus-User-Interface#7]
I would like to update the repository with CODE_OF_CONDUCT file.

**Comment by Dhruv-Davda** [comment]
@vaibhavyadav-dev Can you please assign me this issue ?

**Comment by iitzIrFan** [comment]
@vaibhavyadav-dev Do assign me this issue so that I can work in it !

**Comment by Dhruv-Davda** [comment]
@iitzIrFan Please create your own issues and work on them instead of requesting maintainers to assign you tasks for which others had already initiated issues. 

@vaibhavyadav-dev ,  I hope you will assign this to me as i had issued this issue first. 


Thanks and Regards, 

Dhruv Davda.
